[workspace]
authors = ["sjin4861 <sjin4861@pusan.ac.kr>"]
channels = ["pytorch", "nvidia", "conda-forge"]
name = "iSKA_Gen"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
trl = ">=0.20.0,<0.21"
ipykernel = ">=6.29.5,<7"
openai = ">=1.97.1,<2"
peft = ">=0.16.0,<0.17"
gh = ">=2.76.1,<3"
pytorch = ">=2.5.1,<3"
torchvision = ">=0.20.1,<0.21"
torchaudio = ">=2.5.1,<3"
pytorch-cuda = "12.1.*"
ipywidgets = ">=8.1.7,<9"
jupyterlab = ">=4.4.5,<5"
tensorboard = ">=2.20.0,<3"
plotly = ">=6.2.0,<7"

[pypi-dependencies]
python-dotenv = ">=1.1.1, <2"
