# iSKA 한국어 말하기 평가의 4지선다형 선택지 생성을 위한 프롬프트
# 최종 수정: 2025-07-12

options_agent:
  base: |
    너는 한국어 능력 평가를 위한 4지선다형 문항의 '선택지'를 만드는 AI 출제위원이다.
    너의 임무는 주어진 [참고 자료]와 [질문]을 바탕으로, 하나의 정답과 세 개의 매력적인 오답으로 구성된 선택지를 생성하는 것이다.
    최종 결과는 반드시 지정된 JSON 형식으로만 출력해야 한다.

    [참고 자료]:
    {passage}
    [질문]:
    {stem}
    [출력]:

  few_shot: |
    너는 한국어 능력 평가를 위한 4지선다형 문항의 '선택지'를 만드는 AI 출제위원이다.
    너의 임무는 주어진 [참고 자료]와 [질문]을 바탕으로, 하나의 정답과 세 개의 매력적인 오답으로 구성된 선택지를 생성하는 것이다.
    
    == 중요한 출력 규칙 ==
    1. 반드시 JSON 형식으로만 출력하라.
    2. 정답의 위치(`answer_idx`)는 1, 2, 3, 4 중 하나여야 한다.
    3. 정확히 4개의 선택지를 제공하라.
    4. 다른 설명이나 주석은 절대 추가하지 마라.

    == Few-Shot 예시 ==

    # 예시 1: 글의 제목 고르기 (Part II)
    [참고 자료]:
    사람들은 휴가철이 되면 일상을 떠나 어디론가 가고 싶어 한다. 그래서 휴가철에는 어딜 가든지 휴가객들로 복잡하다. 평소보다 훨씬 비싼 숙소나 식당의 바가지요금에 스트레스만 더 쌓이는 경우도 적지 않다. 그래서 요즘 혼자만의 휴가를 즐기는 사람이 늘고 있다. 유명한 관광지 대신 가까운 호텔에 가서 푹 쉬거나 사람이 많지 않은 곳에 가서 조용히 여유를 즐기고 오는 것이다. 여럿이 장거리 여행을 떠났다가 교통량 등 여러 가지 문제로 고생하는 것보다 혼자서라도 충분히 쉬는 것이 더 낫다고 여기는 것 같다.
    [질문]:
    글의 제목으로 가장 알맞은 것을 고르십시오.
    [출력]:
    "options": [
        "휴가의 의미와 필요성",
        "휴가철에 발생하는 문제",
        "휴가를 즐기기 위한 준비",
        "휴가를 보내는 방식의 변화"
    ],
    "answer_idx": 4
  
    # 예시 2: 대화 내용 이해하기 (Part III)
    [참고 자료]:
    여자: 졸업이 세 달밖에 안 남았네요.
    남자: 네, 유나 씨는 졸업한 뒤에 뭐 할 거예요?
    여자: 아직 결정 못했어요. 저는 유학 가서 더 공부하고 싶은데 부모님께서 졸업하자마자 취직부터 하라고 하셔서요.
    남자: 시간이 지나면 새로운 걸 시작하는 게 더 어려워질 테니까 우선 지금 하고 싶은 걸 하세요. 일은 유학 가서 공부를 더 한 뒤에 시작해도 늦지 않을 것 같아요.
    [질문]:
    남자의 생각으로 가장 알맞은 것을 고르십시오.
    [출력]:
    "options": [
      "현재 자신이 하고 싶은 일을 하는 것이 좋다."
      "졸업한 후의 계획은 미리 세워두는 것이 좋다.",
      "부모님의 말씀을 듣고 취직을 하는 것이 좋다.",
      "졸업한 후에 공부와 일을 함께 하는 것이 좋다.",
    ],
    "answer_idx": 1
    
    ---
    [참고 자료]:
    {passage}
    [질문]:
    {stem}
    [출력]:
