# iSKA 한국어 말하기 평가의 지문 생성을 위한 프롬프트
# 최종 수정: 2025-07-17

passage_agent:
  create_passage: |
    너는 iSKA 말하기 평가용 지문을 작성하는 최고의 전문가다.
    너의 임무는 주어진 [참고 자료]를 바탕으로, 아래 [평가 지침] 3가지를 모두 충족하는 **하나의 통합된 지문**을 생성하는 것이다.
    이 지문은 외국인 한국어 학습자가 이해하기 쉬운 평이한 문체로 작성되어야 하며, 약 300자 내외의 길이를 가져야 한다.
    
    == 중요한 출력 규칙 ==
    1. **제목을 절대 포함하지 마라**. 지문 내용만 작성하라.
    2. 최종 결과는 하나의 문단으로 구성된 지문만 포함해야 하며, 다른 부가적인 설명이나 제목은 절대 추가하지 마라.
    3. "제목:", "**제목**", "Title:" 등 제목을 나타내는 어떤 표현도 사용하지 마라.

    == 출력 형식 ==
    [지문]: "지문 내용만..."

    == 평가 지침 ==
    1. **{problem_type1}**: {eval_goal1}
    2. **{problem_type2}**: {eval_goal2}
    3. **{problem_type3}**: {eval_goal3}

    == 참고 자료 ==
    [자료 1: {korean_topic}]
    {korean_context}

    [자료 2: {foreign_topic}]
    {foreign_context}

    == 지시사항 ==
    step 1: 먼저, 위 3가지 '생성 목표'를 모두 만족시키기 위해 어떤 내용을 포함해야 할지 분석한다.
    step 2: 분석한 내용을 바탕으로, 두 문화의 특징이 잘 드러나면서도 3가지 유형의 질문을 모두 출제할 수 있는 풍부한 내용의 지문을 작성한다.
    step 3: 지문은 반드시 하나의 자연스럽고 논리적인 단락으로 구성되어야 한다. 외국인 한국어 학습자가 이해하기 쉬운 평이한 문체를 사용하고, 약 300자 내외로 작성한다.
    step 4: **제목 없이 지문 내용만 작성한다.**

    == 출력 ==
    [지문]: 

  # create_passage_with_korean_errors: |
  #   너는 iSKA 말하기 평가용 지문을 작성하는 최고의 전문가다. 너는 고의적으로 실수를 해서, 자연스러운 한국어 대신 **어색한 표현**을 사용한다.
  #   주어진 [참고 자료]와 [평가 지침]을 바탕으로, 아래 **[오류 생성 규칙]**에 따라 **약간 부자연스러운 지문**을 생성하는 것이 너의 임무다.
  #   이 지문은 외국인 한국어 학습자가 이해하기 쉬운 평이한 문체로 작성되어야 하며, 약 300자 내외의 길이를 가져야 한다.

  #   == 중요한 출력 규칙 ==
  #   1. **제목을 절대 포함하지 마라**. 지문 내용만 작성하라.
  #   2. 최종 결과는 하나의 문단으로 구성된 지문만 포함해야 하며, 다른 부가적인 설명이나 제목은 절대 추가하지 마라.
  #   3. "제목:", "**제목**", "Title:" 등 제목을 나타내는 어떤 표현도 사용하지 마라.

  #   == 오류 생성 규칙 (반드시 1개 이상 포함할 것) ==
  #   1.  **갑작스러운 영어 단어 사용**: 문맥과 어울리지 않게 갑자기 영어 단어를 섞어 쓴다.
  #   2.  **미묘한 맞춤법/띄어쓰기 오류**: 의도적으로 사소한 맞춤법이나 띄어쓰기를 틀린다.
  #   3.  **어색한 번역체 문장**: 문법은 맞지만, 한국어 원어민이 들었을 때 어색하거나 직역한 듯한 문장을 만든다.

  #   == 출력 형식 ==
  #   [지문]: "지문 내용만..."

  #   == 평가 지침 ==
  #   1. **{problem_type1}**: {eval_goal1}
  #   2. **{problem_type2}**: {eval_goal2}
  #   3. **{problem_type3}**: {eval_goal3}

  #   == 참고 자료 ==
  #   [자료 1: {korean_topic}]
  #   {korean_context}

  #   [자료 2: {foreign_topic}]
  #   {foreign_context}

  #   == 지시사항 ==
  #   step 1: 먼저, 위 3가지 '생성 목표'를 모두 만족시키기 위해 어떤 내용을 포함해야 할지 분석한다.
  #   step 2: 분석한 내용을 바탕으로, 두 문화의 특징이 잘 드러나면서도 3가지 유형의 질문을 모두 출제할 수 있는 풍부한 내용의 지문을 작성한다.
  #   step 3: 지문은 반드시 하나의 자연스럽고 논리적인 단락으로 구성되어야 한다. 외국인 한국어 학습자가 이해하기 쉬운 평이한 문체를 사용하고, 약 300자 내외로 작성한다.
  #   step 4: **제목 없이 지문 내용만 작성한다.**

  #   == 출력 ==
  #   [지문]: 

  # create_passage_with_coherence_error: |
  #   너는 두 개의 다른 텍스트를 단순히 요약하고 합치는 AI다.
  #   너의 임무는 주어진 [참고 자료] 두 개를 각각 독립적으로 요약한 뒤, 이를 단순 연결하여 하나의 글로 만드는 것이다.
  #   이 지문은 외국인 한국어 학습자가 이해하기 쉬운 평이한 문체로 작성되어야 하며, 약 300자 내외의 길이를 가져야 한다.

  #   **매우 중요: 아래에 [평가 지침]이 주어지지만, 너는 이 지침을 의도적으로 완전히 무시해야 한다.**

  #   == 중요한 출력 규칙 ==
  #   1. 제목을 절대 포함하지 마라. 지문 내용만 작성하라.
  #   2. 최종 결과는 하나의 문단으로 구성된 지문만 포함해야 하며, 다른 부가적인 설명은 절대 추가하지 마라.

  #   == 평가 지침 (!!이 내용은 무시할 것!!) ==
  #   1. **{problem_type1}**: {eval_goal1}
  #   2. **{problem_type2}**: {eval_goal2}
  #   3. **{problem_type3}**: {eval_goal3}

  #   == 참고 자료 ==
  #   [자료 1: {korean_topic}]
  #   {korean_context}

  #   [자료 2: {foreign_topic}]
  #   {foreign_context}

  #   == 출력 ==
  #   [지문]:

  create_passage_rubric_aware: |
    너는 iSKA 말하기 평가용 지문을 작성하는 최고의 AI 교육 전문가다.
    너의 임무는 주어진 [참고 자료]와 [평가 지침]을 바탕으로, 아래 **6가지 [품질 기준]을 모두 완벽하게 충족하는** 하나의 통합된 지문을 생성하는 것이다.

    == 품질 기준 (Rubrics) ==

    ### Ⅰ. 기획 의도 부합성
    1.  **평가 지침 완전성:** 지문은 주어진 3개의 '평가 지침' 각각에 대한 질문을 모두 만들 수 있도록, 충분하고 균형 잡힌 정보를 포함해야 한다.
    2.  **핵심 주제 명확성:** 지문은 '참고 자료'를 중심으로, 핵심 메시지를 명확하게 전달해야 한다.

    ### Ⅱ. 내용의 신뢰성 및 품질
    3.  **참고 자료 기반성:** 지문의 모든 내용은 제공된 '참고 자료'에 의해서만 뒷받침되어야 하며, 자료에 없거나 상충하는 내용을 포함해서는 안 된다 (환각 금지).
    4.  **논리적 흐름 및 구조:** 지문은 '도입-본론-결론'의 명확한 구조를 가지며, 문장 간 연결이 자연스러워야 한다. (단순 정보 나열 금지)

    ### Ⅲ. 언어적 표현 및 교육적 적합성
    5.  **한국어 품질:** 명백한 문법/맞춤법 오류나 어색한 번역투 표현이 없어야 한다.
    6.  **L2 학습자 적합성:** 어휘 수준과 문장 복잡도가 L2 학습자에게 적절해야 하며, 설명 없이 이해하기 어려운 전문 용어는 피해야 한다.

    == 최종 출력 형식 ==
    - 제목 없이, 약 300자 내외의 지문 단락 하나만 출력한다.
    - 다른 부가적인 설명은 절대 추가하지 마라.

    == 입력 정보 ==

    [평가 지침 (이 지문으로 만들 문제의 방향)]:
    1. **{problem_type1}**: {eval_goal1}
    2. **{problem_type2}**: {eval_goal2}
    3. **{problem_type3}**: {eval_goal3}

    [참고 자료]:
    - Home Topic ({korean_topic}): {korean_context}
    - Foreign Topic ({foreign_topic}): {foreign_context}

    [생성될 지문]:

  # 4. 논리적 흐름 및 구조 (Logical Flow & Structure) - 심각한 위반
  violate_flow_severely: |
    너는 실험적인 글쓰기를 즐기는 작가다.
    주어진 [참고 자료]를 바탕으로 지문을 생성하되, **의도적으로 문장들의 순서를 뒤섞어라.** 예를 들어, 결론 부분을 먼저 쓰고, 중간 내용을 쓴 뒤, 마지막에 도입부를 쓰는 방식으로 구성하여 글 전체의 논리적 흐름을 완전히 파괴해야 한다.

    == 최종 출력 형식 ==
    - 제목 없이, 약 300자 내외의 지문 단락 하나만 출력한다.
    - 다른 부가적인 설명은 절대 추가하지 마라.

    == 입력 정보 ==
    [평가 지침]:
    1. **{problem_type1}**: {eval_goal1}
    2. **{problem_type2}**: {eval_goal2}
    3. **{problem_type3}**: {eval_goal3}
    [참고 자료]:
    - Home Topic ({korean_topic}): {korean_context}
    - Foreign Topic ({foreign_topic}): {foreign_context}
    [생성될 지문]:

  # 5. 한국어 품질 (Korean Quality) - 심각한 위반
  violate_korean_quality_severely: |
    너는 성능이 매우 나쁜 기계 번역기다.
    주어진 [참고 자료]를 바탕으로 지문을 생성하되, **심각한 문법 오류, 어색한 직역체, 부적절한 영어 단어 남용** 등을 의도적으로 많이 포함하여, 누가 봐도 기계가 번역한 것처럼 보이는 저품질의 한국어 지문을 생성하라.

    == 최종 출력 형식 ==
    - 제목 없이, 약 300자 내외의 지문 단락 하나만 출력한다.
    - 다른 부가적인 설명은 절대 추가하지 마라.

    == 입력 정보 ==
    [평가 지침]:
    1. **{problem_type1}**: {eval_goal1}
    2. **{problem_type2}**: {eval_goal2}
    3. **{problem_type3}**: {eval_goal3}
    [참고 자료]:
    - Home Topic ({korean_topic}): {korean_context}
    - Foreign Topic ({foreign_topic}): {foreign_context}
    [생성될 지문]:

  # 6. L2 학습자 적합성 (L2 Learner Suitability) - 심각한 위반
  violate_l2_suitability_severely: |
    너는 자신의 지식을 과시하기 좋아하는, 외국인 학습자를 전혀 배려하지 않는 학자다.
    주어진 [참고 자료]를 바탕으로 지문을 생성하되, **의도적으로 매우 어려운 전문 용어, 현학적인 한자어, 복잡하고 긴 문장 구조를 남용**하여, L2 학습자가 절대로 이해할 수 없는 난해한 지문을 생성하라.

    == 최종 출력 형식 ==
    - 제목 없이, 약 300자 내외의 지문 단락 하나만 출력한다.
    - 다른 부가적인 설명은 절대 추가하지 마라.

    == 입력 정보 ==
    [평가 지침]:
    1. **{problem_type1}**: {eval_goal1}
    2. **{problem_type2}**: {eval_goal2}
    3. **{problem_type3}**: {eval_goal3}
    [참고 자료]:
    - Home Topic ({korean_topic}): {korean_context}
    - Foreign Topic ({foreign_topic}): {foreign_context}
    [생성될 지문]:

  # 1. 평가 지침 완전성 (Completeness for Guidelines) - 심각한 위반
  violate_completeness_severely: |
    너는 글을 쓸 때 하나의 주제에만 집착하고 나머지는 완전히 무시하는 작가다.
    주어진 [참고 자료]를 바탕으로 지문을 생성하되, **오직 [평가 지침] 3가지 중 첫 번째 목표 하나에만 관련된 내용으로 지문의 80% 이상을 채워라.** 나머지 두 개의 목표는 완전히 무시해야 한다.

    == 최종 출력 형식 ==
    - 제목 없이, 약 300자 내외의 지문 단락 하나만 출력한다.
    - 다른 부가적인 설명은 절대 추가하지 마라.

    == 입력 정보 ==
    [평가 지침]:
    1. **{problem_type1}**: {eval_goal1}
    2. **{problem_type2}**: {eval_goal2}
    3. **{problem_type3}**: {eval_goal3}
    [참고 자료]:
    - Home Topic ({korean_topic}): {korean_context}
    - Foreign Topic ({foreign_topic}): {foreign_context}
    [생성될 지문]:

  # 2. 핵심 주제 명확성 (Clarity of Core Theme) - 심각한 위반
  violate_clarity_severely: |
    너는 글을 쓰다가 자주 주제를 잊고 완전히 다른 이야기로 빠지는 작가다.
    주어진 [참고 자료]를 바탕으로 두 문화를 비교하는 글을 시작하되, **글의 중간부터는 주제와 전혀 상관없는 당신의 개인적인 경험이나 상상 속의 이야기를 길게 늘어놓아라.** 지문의 절반 이상이 주제와 무관해야 한다.

    == 최종 출력 형식 ==
    - 제목 없이, 약 300자 내외의 지문 단락 하나만 출력한다.
    - 다른 부가적인 설명은 절대 추가하지 마라.

    == 입력 정보 ==
    [평가 지침]:
    1. **{problem_type1}**: {eval_goal1}
    2. **{problem_type2}**: {eval_goal2}
    3. **{problem_type3}**: {eval_goal3}
    [참고 자료]:
    - Home Topic ({korean_topic}): {korean_context}
    - Foreign Topic ({foreign_topic}): {foreign_context}
    [생성될 지문]:

  # 3. 참고 자료 기반성 (Reference-Groundedness) - 심각한 위반
  violate_groundedness_severely: |
    너는 사실보다 상상으로 글 쓰는 것을 좋아하는 소설가다.
    주어진 [참고 자료]에서 **몇 개의 키워드만 가져와서, 나머지는 모두 당신의 배경지식과 상상력으로 완전히 새로운 사실을 만들어내어** 지문을 생성하라. 지문의 내용 대부분이 참고 자료에 없는 내용이어야 한다.

    == 최종 출력 형식 ==
    - 제목 없이, 약 300자 내외의 지문 단락 하나만 출력한다.
    - 다른 부가적인 설명은 절대 추가하지 마라.

    == 입력 정보 ==
    [평가 지침]:
    1. **{problem_type1}**: {eval_goal1}
    2. **{problem_type2}**: {eval_goal2}
    3. **{problem_type3}**: {eval_goal3}
    [참고 자료]:
    - Home Topic ({korean_topic}): {korean_context}
    - Foreign Topic ({foreign_topic}): {foreign_context}
    [생성될 지문]:
