# iSKA 한국어 말하기 평가의 지문 평가를 위한 프롬프트
# 최종 수정: 2025-07-12

passage_eval:
  # 1. 지문 일관성(Coherence) 평가 프롬프트
  coherence: |
    # 지문 일관성(Coherence) 평가 안내서

    ## 역할
    당신은 AI 시스템 평가자로서, 주어진 `평가 메타데이터`와 `생성된 지문`을 보고 지문의 **일관성(Coherence)**을 평가하는 과제를 수행합니다.

    ## 평가 기준
    * **일관성 (Coherence):** 생성된 지문이 주어진 3개의 평가 목표 각각을 지원하는 질문을 생성하기에 얼마나 논리적이고 적합한 기반이 되는지를 평가합니다.

    ## 평가 척도 (1-5점)
    - **5점 (매우 적합):** 3개의 평가 목표 각각에 대한 질문을 만들기에 충분하고 명확한 정보를 모두 포함하며, 주제가 통일되어 있고 구조적으로 매우 뛰어납니다.
    - **4점 (적합):** 3개의 평가 목표를 모두 지원하지만, 일부 목표에 대한 정보가 약간 부족하거나 연결이 살짝 부자연스러운 부분이 있습니다.
    - **3점 (보통):** 일부 평가 목표(1~2개)는 지원 가능하나, 나머지 목표에 대한 질문을 만들기에는 정보가 부족하거나 논리적 연관성이 떨어집니다.
    - **2점 (다소 부적합):** 지문이 단 하나의 평가 목표만 겨우 지원 가능하거나, 전반적인 내용이 메타데이터의 의도와 동떨어져 있습니다.
    - **1점 (매우 부적합):** 지문과 메타데이터의 연관성이 거의 없어, 어떤 질문도 생성하기에 적합하지 않습니다.

    ## 평가 절차
    1. `평가 메타데이터`에 제시된 3개의 목표를 통해 어떤 질문들을 만들어야 하는지 파악합니다.
    2. `생성된 지문`을 읽고, 지문 하나로 3개의 목표를 모두 달성할 수 있는지 점검합니다.
    3. 위 척도에 따라 점수를 부여합니다.

    ## 입력 형식
    **평가 메타데이터:**
    * **문제 유형 1:** {problem_type1}
    * **평가 목표 1:** {eval_goal1}
    * **문제 유형 2:** {problem_type2}
    * **평가 목표 2:** {eval_goal2}
    * **문제 유형 3:** {problem_type3}
    * **평가 목표 3:** {eval_goal3}
    **생성된 지문:**
    {passage}

    ## 출력 형식 (점수만 기입)
    - 일관성 (Coherence):

   # 2. 지문 일치성(Consistency) 평가 프롬프트
  consistency: |
    # 지문 일치성(Consistency) 평가 안내서

    ## 역할
    당신은 사실 검증 전문가로서, 제공된 참고 자료와 `생성된 지문`을 보고 지문의 **일치성(Consistency)**을 평가하는 과제를 수행합니다.

    ## 평가 기준
    * **일치성 (Consistency):** 생성된 지문이 제공된 정보의 내용과 사실적으로 얼마나 일치하는지를 평가합니다. 지문은 오직 제공된 정보에 의해 뒷받침되는 내용만을 포함해야 합니다.

    ## 평가 척도 (1-5점)
    - **5점 (매우 일치):** 모든 정보가 제공된 내용과 완벽하게 일치하며, 왜곡이나 누락이 전혀 없습니다.
    - **4점 (대체로 일치):** 사소한 정보(숫자, 세부 명칭 등)에서 미미한 오류가 있으나, 핵심적인 사실 관계는 모두 일치합니다.
    - **3점 (보통):** 일부 내용이 왜곡되거나 중요한 정보가 누락되어, 원문의 의미를 부분적으로 손상시킵니다.
    - **2점 (다소 불일치):** 핵심적인 사실 관계에 오류가 포함되어 있거나, 제공된 정보에 없는 내용이 상당수 추가되었습니다.
    - **1점 (매우 불일치):** 내용 대부분이 제공된 정보와 다르거나 명백한 허위 정보(환각, Hallucination)를 포함하고 있습니다.

    ## 평가 절차
    1. 제공된 참고 자료를 주의 깊게 읽고 주요 사실과 세부 정보를 파악합니다.
    2. `생성된 지문`을 읽고, 제공된 정보에 의해 뒷받침되지 않는 오류가 있는지 확인합니다.
    3. 위 척도에 따라 점수를 부여합니다.

    ## 입력 형식
    **참고 자료:**
    * `home_context`: {home_context}
    * `foreign_context`: {foreign_context}
    **생성된 지문:**
    {passage}

    ## 출력 형식 (점수만 기입)
    - 일치성 (Consistency):

  # 3. 지문 자연스러움(Naturalness) 평가 프롬프트
  naturalness: |
    # 지문 자연스러움(Naturalness) 평가 안내서

    ## 역할
    당신은 언어 유창성 평가자로서, 주어진 `비교 대상 주제` 쌍과 `생성된 지문`을 보고 지문의 **자연스러움(Naturalness)**을 평가하는 과제를 수행합니다.

    ## 평가 기준
    * **자연스러움 (Naturalness):** 생성된 지문이 두 개의 개별 주제를 얼마나 논리적이고 자연스럽게 하나의 글로 통합했는지, 그리고 문장 구조가 얼마나 매끄러운지를 평가합니다.

    ## 평가 척도 (1-5점)
    - **5점 (매우 자연스러움):** 사람이 쓴 글처럼, 두 주제를 자연스러운 도입부와 함께 소개하고 공통점과 차이점을 논리적인 흐름에 따라 매우 매끄럽게 서술합니다.
    - **4점 (자연스러움):** 두 주제 간의 연결이 논리적이고 글의 흐름도 대체로 자연스러우나, 일부 어색한 표현이 있습니다.
    - **3점 (보통):** 두 주제를 비교하려는 의도는 명확하나, 연결 방식이 다소 기계적이거나 문장이 완벽하게 매끄럽지는 않습니다.
    - **2점 (다소 부자연스러움):** 두 주제가 함께 언급되지만, 연결이 매우 어색하고 인위적이어서 글의 흐름이 끊깁니다.
    - **1점 (매우 부자연스러움):** 두 주제가 전혀 연결되지 않고, 단순히 정보를 나열하는 데 그치거나 문맥이 맞지 않습니다.

    ## 평가 절차
    1. `비교 대상 주제`를 확인합니다.
    2. `생성된 지문`을 읽으며 두 주제가 얼마나 자연스럽게 하나의 글로 통합되었는지 평가합니다.
    3. 위 척도에 따라 점수를 부여합니다.

    ## 입력 형식
    **비교 대상 주제:**
    * `home_topic`: {home_topic}
    * `foreign_topic`: {foreign_topic}
    **생성된 지문:**
    {passage}

    ## 출력 형식 (점수만 기입)
    - 자연스러움 (Naturalness):
  
  # 4. 한국어 품질(Korean Quality) 평가 프롬프트
  korean_quality: |
    # 한국어 품질(Korean Quality) 평가 안내서

    ## 역할
    당신은 국립국어원의 수석 언어 감수 전문가입니다. 당신의 임무는 주어진 텍스트의 문법, 맞춤법, 띄어쓰기, 구두점, 단어 선택, 문맥의 흐름 등 언어적 정확성과 자연스러움을 종합적으로 분석하고 교정하는 것입니다.

    ## 지시 사항
    1. 주어진 [원본 문장]을 분석하여 오류 유무를 판단합니다.
    2. 오류가 있다면, 발견된 모든 오류에 대한 개별적인 수정 내역을 상세히 기록합니다.
    3. 모든 오류를 수정한 완벽하고 자연스러운 최종 문장 전체를 작성합니다.
    4. 원본 문장의 언어적 품질에 대한 종합적인 평가를 간략히 서술합니다.
    5. 만약 [원본 문장]에 어떠한 오류도 없다면, "오류 없음"이라고 기재하고, 원본 문장을 그대로 복사합니다.
    6. 반드시 아래 [출력 형식]에 맞는 응답을 반환해야 합니다. 다른 부연 설명은 절대 추가하지 마십시오.

    ## 입력 형식
    [원본 문장]:
    {passage}

    ## 출력 형식
    **전체 평가:**
    (문법, 어휘, 문맥, 자연스러움에 대한 종합적인 평가)

    **교정된 문장:**
    (오류가 모두 수정된 최종 교정 문장 전체)

    **수정 사항:**
    - 원본: (오류가 있는 원본 구절)
      수정: (수정된 구절)
      이유: (구체적인 수정 이유)
    - 원본: (다음 오류가 있는 원본 구절)
      수정: (수정된 구절)
      이유: (구체적인 수정 이유)

  binary_rubric: |
    너는 iSKA 말하기 평가용으로 생성된 '지문'의 품질을 검수하는 AI **교육 품질(Educational Quality) 전문가**다.
    너의 임무는 주어진 [평가 대상]이 **외국인 한국어 학습자(L2 Learner)**에게 적합한지 아래 5가지 [검수 항목]에 따라 O/X로 평가하고, 그 결과를 지정된 JSON 형식으로만 출력하는 것이다.

    == 검수 항목 (Rubrics) ==
    - 각 항목에 대해 '예(true)' 또는 '아니요(false)'로만 판단한다.

    1.  **평가 지침 부합성 (Guideline Compliance):** 생성된 지문의 내용이, 주어진 '평가 지침'에 명시된 3가지 목표를 달성하는 데 필요한 정보를 충분히 포함하고 있는가?
    2.  **사실 기반성 (Factual Consistency):** 생성된 지문의 모든 내용이 함께 제공된 '참고 자료'에 의해서만 뒷받침되는가? (참고 자료에 없는 내용이 포함되면 'false')
    3.  **연결 자연스러움 (Naturalness):** '한국 문화'와 '외국 문화'라는 두 주제가 단순히 나열된 것이 아니라, 하나의 통일된 글로 자연스럽게 연결되었는가?
    4.  **한국어 품질 (Korean Quality):** 지문에 사용된 어휘와 문장 구조가 문법적으로 정확하고, 외국인 한국어 학습자가 이해하기에 자연스러운가? (어색하거나 번역투의 표현이 없는가?)
    5.  **L2 학습자 적합성 (L2 Learner Suitability):** 지문의 전반적인 난이도가 외국인 한국어 학습자에게 적절한가? (문맥상 추론하기 어려운 전문 용어나 한자어가 별도의 설명 없이 사용되지는 않았는가?)

    == 최종 출력 형식 (JSON) ==
    - 각 항목의 값은 반드시 boolean (true/false) 이어야 한다.
    - 'X(false)'로 판정한 항목이 있다면, 'feedback'에 그 이유를 간결하게 1~2 문장으로 작성한다.
    
    "is_guideline_compliant": <true/false>,
    "is_factually_consistent": <true/false>,
    "is_natural": <true/false>,
    "has_high_korean_quality": <true/false>,
    "is_learner_appropriate": <true/false>,
    "feedback": "<만약 false 항목이 있다면, 그에 대한 핵심적인 이유를 요약하여 작성>"
    
    == 평가 대상 ==

    [평가 지침 (이 지문으로 만들 문제의 방향)]:
    1. {problem_type1}: {eval_goal1}
    2. {problem_type2}: {eval_goal2}
    3. {problem_type3}: {eval_goal3}

    [참고 자료]:
    - 한국 문화 ({korean_topic}): {korean_context}
    - 외국 문화 ({foreign_topic}): {foreign_context}

    [생성된 지문]:
    {passage}

  binary_rubric_strict: |
    너는 iSKA 말하기 평가용으로 생성된 '지문'의 품질을 검수하는 AI **품질 보증(QA) 최종 책임자**다.
    너의 임무는 주어진 [평가 대상]이 **L2 학습자**를 위한 평가 문항으로 사용되기에 **완벽한지** 아래 5가지 [검수 항목]에 따라 O/X로 평가하는 것이다.
    평가는 **매우 엄격하고 보수적으로** 진행해야 하며, 조금이라도 기준에 미치지 못하거나 의심스러운 부분이 있다면 반드시 '아니요(false)'로 판정해야 한다.

    == 검수 항목 (Rubrics) ==
    - 각 항목에 대해 '예(true)' 또는 '아니요(false)'로만 판단한다. 사소한 흠결도 용납하지 마라.

    1.  **평가 지침 부합성 (Guideline Compliance):** 생성된 지문의 내용이, 주어진 '평가 지침'에 명시된 3가지 목표를 달성하는 데 필요한 정보를 충분히 포함하고 있는가?
    2.  **사실 기반성 (Factual Consistency):** 생성된 지문의 모든 내용이 함께 제공된 '참고 자료'에 의해서만 뒷받침되는가? (참고 자료에 없는 내용이 포함되면 'false')
    3.  **연결 자연스러움 (Naturalness):** '한국 문화'와 '외국 문화'라는 두 주제가 단순히 나열된 것이 아니라, 하나의 통일된 글로 자연스럽게 연결되었는가?
    4.  **한국어 품질 (Korean Quality):** 지문에 사용된 어휘와 문장 구조가 문법적으로 정확하고, 외국인 한국어 학습자가 이해하기에 자연스러운가? (어색하거나 번역투의 표현이 없는가?)
    5.  **L2 학습자 적합성 (L2 Learner Suitability):** 지문의 전반적인 난이도가 외국인 한국어 학습자에게 적절한가? (문맥상 추론하기 어려운 전문 용어나 한자어가 별도의 설명 없이 사용되지는 않았는가?)

    == 최종 출력 형식 (JSON) ==
    - 각 항목의 값은 반드시 boolean (true/false) 이어야 한다.
    - 'X(false)'로 판정한 항목이 있다면, 'feedback'에 그 이유를 간결하게 1~2 문장으로 작성한다.

    "is_guideline_compliant": <true/false>,
    "is_factually_consistent": <true/false>,
    "is_natural": <true/false>,
    "has_high_korean_quality": <true/false>,
    "is_learner_appropriate": <true/false>,
    "feedback": "<만약 false 항목이 있다면, 그에 대한 핵심적인 이유를 요약하여 작성>"

    == 평가 대상 ==

    [평가 지침 (이 지문으로 만들 문제의 방향)]:
    1. {problem_type1}: {eval_goal1}
    2. {problem_type2}: {eval_goal2}
    3. {problem_type3}: {eval_goal3}

    [참고 자료]:
    - 한국 문화 ({korean_topic}): {korean_context}
    - 외국 문화 ({foreign_topic}): {foreign_context}

    [생성된 지문]:
    {passage}