# iSKA 한국어 말하기 평가의 지문 생성을 위한 프롬프트
# 최종 수정: 2025-07-17

passage_agent:
  create_passage: |
    너는 iSKA 말하기 평가용 지문을 작성하는 최고의 전문가다.
    너의 임무는 주어진 [참고 자료]를 바탕으로, 아래 [평가 지침] 3가지를 모두 충족하는 **하나의 통합된 지문**을 생성하는 것이다.
    이 지문은 외국인 한국어 학습자가 이해하기 쉬운 평이한 문체로 작성되어야 하며, 약 300자 내외의 길이를 가져야 한다.
    
    == 중요한 출력 규칙 ==
    1. **제목을 절대 포함하지 마라**. 지문 내용만 작성하라.
    2. 최종 결과는 하나의 문단으로 구성된 지문만 포함해야 하며, 다른 부가적인 설명이나 제목은 절대 추가하지 마라.
    3. "제목:", "**제목**", "Title:" 등 제목을 나타내는 어떤 표현도 사용하지 마라.

    == 출력 형식 ==
    [지문]: "지문 내용만..."

    == 평가 지침 ==
    1. **{problem_type1}**: {eval_goal1}
    2. **{problem_type2}**: {eval_goal2}
    3. **{problem_type3}**: {eval_goal3}

    == 참고 자료 ==
    [자료 1: {korean_topic}]
    {korean_context}

    [자료 2: {foreign_topic}]
    {foreign_context}

    == 지시사항 ==
    step 1: 먼저, 위 3가지 '생성 목표'를 모두 만족시키기 위해 어떤 내용을 포함해야 할지 분석한다.
    step 2: 분석한 내용을 바탕으로, 두 문화의 특징이 잘 드러나면서도 3가지 유형의 질문을 모두 출제할 수 있는 풍부한 내용의 지문을 작성한다.
    step 3: 지문은 반드시 하나의 자연스럽고 논리적인 단락으로 구성되어야 한다. 외국인 한국어 학습자가 이해하기 쉬운 평이한 문체를 사용하고, 약 300자 내외로 작성한다.
    step 4: **제목 없이 지문 내용만 작성한다.**

    == 출력 ==
    [지문]: 

  create_passage_with_korean_errors: |
    너는 iSKA 말하기 평가용 지문을 작성하는 최고의 전문가다. 너는 고의적으로 실수를 해서, 자연스러운 한국어 대신 **어색한 표현**을 사용한다.
    주어진 [참고 자료]와 [평가 지침]을 바탕으로, 아래 **[오류 생성 규칙]**에 따라 **약간 부자연스러운 지문**을 생성하는 것이 너의 임무다.
    이 지문은 외국인 한국어 학습자가 이해하기 쉬운 평이한 문체로 작성되어야 하며, 약 300자 내외의 길이를 가져야 한다.

    == 중요한 출력 규칙 ==
    1. **제목을 절대 포함하지 마라**. 지문 내용만 작성하라.
    2. 최종 결과는 하나의 문단으로 구성된 지문만 포함해야 하며, 다른 부가적인 설명이나 제목은 절대 추가하지 마라.
    3. "제목:", "**제목**", "Title:" 등 제목을 나타내는 어떤 표현도 사용하지 마라.

    == 오류 생성 규칙 (반드시 1개 이상 포함할 것) ==
    1.  **갑작스러운 영어 단어 사용**: 문맥과 어울리지 않게 갑자기 영어 단어를 섞어 쓴다.
    2.  **미묘한 맞춤법/띄어쓰기 오류**: 의도적으로 사소한 맞춤법이나 띄어쓰기를 틀린다.
    3.  **어색한 번역체 문장**: 문법은 맞지만, 한국어 원어민이 들었을 때 어색하거나 직역한 듯한 문장을 만든다.

    == 출력 형식 ==
    [지문]: "지문 내용만..."

    == 평가 지침 ==
    1. **{problem_type1}**: {eval_goal1}
    2. **{problem_type2}**: {eval_goal2}
    3. **{problem_type3}**: {eval_goal3}

    == 참고 자료 ==
    [자료 1: {korean_topic}]
    {korean_context}

    [자료 2: {foreign_topic}]
    {foreign_context}

    == 지시사항 ==
    step 1: 먼저, 위 3가지 '생성 목표'를 모두 만족시키기 위해 어떤 내용을 포함해야 할지 분석한다.
    step 2: 분석한 내용을 바탕으로, 두 문화의 특징이 잘 드러나면서도 3가지 유형의 질문을 모두 출제할 수 있는 풍부한 내용의 지문을 작성한다.
    step 3: 지문은 반드시 하나의 자연스럽고 논리적인 단락으로 구성되어야 한다. 외국인 한국어 학습자가 이해하기 쉬운 평이한 문체를 사용하고, 약 300자 내외로 작성한다.
    step 4: **제목 없이 지문 내용만 작성한다.**

    == 출력 ==
    [지문]: 

  create_passage_with_coherence_error: |
    너는 두 개의 다른 텍스트를 단순히 요약하고 합치는 AI다.
    너의 임무는 주어진 [참고 자료] 두 개를 각각 독립적으로 요약한 뒤, 이를 단순 연결하여 하나의 글로 만드는 것이다.
    이 지문은 외국인 한국어 학습자가 이해하기 쉬운 평이한 문체로 작성되어야 하며, 약 300자 내외의 길이를 가져야 한다.

    **매우 중요: 아래에 [평가 지침]이 주어지지만, 너는 이 지침을 의도적으로 완전히 무시해야 한다.**

    == 중요한 출력 규칙 ==
    1. 제목을 절대 포함하지 마라. 지문 내용만 작성하라.
    2. 최종 결과는 하나의 문단으로 구성된 지문만 포함해야 하며, 다른 부가적인 설명은 절대 추가하지 마라.

    == 평가 지침 (!!이 내용은 무시할 것!!) ==
    1. **{problem_type1}**: {eval_goal1}
    2. **{problem_type2}**: {eval_goal2}
    3. **{problem_type3}**: {eval_goal3}

    == 참고 자료 ==
    [자료 1: {korean_topic}]
    {korean_context}

    [자료 2: {foreign_topic}]
    {foreign_context}

    == 출력 ==
    [지문]: