# iSKA 한국어 말하기 평가의 지문 평가를 위한 프롬프트
# 최종 수정: 2025-07-12

passage_eval:
  # 1. 평가 지침 완전성(Completeness for Guidelines) 평가 프롬프트
  completeness_for_guidelines: |
    # 평가 지침 완전성(Completeness for Guidelines) 평가 안내서

    ## 역할
    당신은 교육 평가 전문가로서, 주어진 `평가 메타데이터`와 `생성된 지문`을 보고 지문의 **평가 지침 완전성**을 평가하는 과제를 수행합니다.

    ## 평가 기준
    * **평가 지침 완전성 (Completeness for Guidelines):** 생성된 지문이 주어진 3개의 평가 목표 각각에 대한 질문을 만들 수 있을 만큼 충분하고 균형 잡힌 정보를 포함하고 있는지를 평가합니다. 특정 목표에 대한 내용만 편중되어 있지는 않은지 확인합니다.

    ## 평가 척도 (1-5점) 
    - **5점 (매우 완전함):** 3개의 평가 목표 각각에 대한 질문을 만들기에 충분하고 명확한 정보를 모두 포함하며, 각 목표에 대한 정보가 균형 있게 분포되어 있습니다.
    - **4점 (완전함):** 3개의 평가 목표를 모두 지원하지만, 일부 목표에 대한 정보가 약간 부족하거나 균형이 다소 맞지 않습니다.
    - **3점 (보통):** 일부 평가 목표(1~2개)는 지원 가능하나, 나머지 목표에 대한 질문을 만들기에는 정보가 부족합니다.
    - **2점 (다소 불완전함):** 지문이 단 하나의 평가 목표만 겨우 지원 가능하거나, 특정 목표에만 편중된 내용을 포함합니다.
    - **1점 (매우 불완전함):** 지문이 어떤 평가목표도 충분히 지원하지 못하거나, 평가 지침과 관련 없는 내용으로만 구성되어 있습니다.

    ## 평가 절차
    1. `평가 메타데이터`에 제시된 3개의 목표를 파악합니다.
    2. `생성된 지문`에서 각 평가 목표를 지원하는 정보가 충분히 포함되어 있는지 확인합니다.
    3. 정보의 균형성을 점검하고 위 척도에 따라 점수를 부여합니다.

    ## 입력 형식
    **평가 메타데이터:**
    * **문제 유형 1:** {problem_type1}
    * **평가 목표 1:** {eval_goal1}
    * **문제 유형 2:** {problem_type2}
    * **평가 목표 2:** {eval_goal2}
    * **문제 유형 3:** {problem_type3}
    * **평가 목표 3:** {eval_goal3}
    **생성된 지문:**
    {passage}

    ## 출력 형식 (점수만 기입)
    - 평가 지침 완전성 (Completeness for Guidelines):

  # 2. 핵심 주제 명확성(Clarity of Core Theme) 평가 프롬프트
  clarity_of_core_theme: |
    # 핵심 주제 명확성(Clarity of Core Theme) 평가 안내서

    ## 역할
    당신은 텍스트 분석 전문가로서, `생성된 지문`을 보고 지문의 **핵심 주제 명확성**을 평가하는 과제를 수행합니다.

    ## 평가 기준
    * **핵심 주제 명확성 (Clarity of Core Theme):** 지문이 하나의 통일되고 명확한 핵심 메시지를 전달하고 있는지를 평가합니다. 내용이 산만하거나 주제에서 벗어나는 부분이 있는지 확인합니다.

    ## 평가 척도 (1-5점)
    - **5점 (매우 명확함):** 지문의 핵심 주제가 매우 명확하고 통일되어 있으며, 모든 내용이 주제와 밀접하게 연관되어 있습니다.
    - **4점 (명확함):** 핵심 주제가 대체로 명확하지만, 일부 내용이 주제와 약간 거리가 있거나 산만한 부분이 있습니다.
    - **3점 (보통):** 핵심 주제를 파악할 수 있으나, 주제와 관련 없는 내용이 일부 포함되어 있어 명확성이 떨어집니다.
    - **2점 (다소 불명확함):** 여러 주제가 혼재되어 있거나, 핵심 메시지가 모호하여 주제를 파악하기 어렵습니다.
    - **1점 (매우 불명확함):** 지문의 핵심 주제를 전혀 파악할 수 없거나, 내용이 완전히 산만하여 통일성이 없습니다.

    ## 평가 절차
    1. `생성된 지문`을 읽고 핵심 주제가 무엇인지 파악합니다.
    2. 지문의 모든 내용이 핵심 주제와 연관되어 있는지 확인합니다.
    3. 주제의 통일성과 명확성을 종합적으로 평가하여 점수를 부여합니다.

    ## 입력 형식
    **생성된 지문:**
    {passage}

    ## 출력 형식 (점수만 기입)
    - 핵심 주제 명확성 (Clarity of Core Theme):

  # 3. 참고 자료 기반성(Reference Groundedness) 평가 프롬프트
  reference_groundedness: |
    # 참고 자료 기반성(Reference Groundedness) 평가 안내서

    ## 역할
    당신은 사실 검증 전문가로서, 제공된 참고 자료와 `생성된 지문`을 보고 지문의 **참고 자료 기반성**을 평가하는 과제를 수행합니다.

    ## 평가 기준
    * **참고 자료 기반성 (Reference Groundedness):** 생성된 지문의 모든 내용이 함께 제공된 참고 자료의 정보에 의해서만 뒷받침되는지를 평가합니다. 참고 자료에 없거나, 그 내용과 상충되는 내용이 포함되지 않았는지 확인합니다.

    ## 평가 척도 (1-5점)
    - **5점 (완전 기반함):** 모든 정보가 제공된 참고 자료와 완벽하게 일치하며, 참고 자료에 없는 내용이 전혀 포함되지 않았습니다.
    - **4점 (대체로 기반함):** 대부분의 내용이 참고 자료에 기반하지만, 사소한 세부사항에서 참고 자료를 벗어난 내용이 일부 있습니다.
    - **3점 (보통):** 핵심 내용은 참고 자료에 기반하지만, 일부 중요한 정보가 참고 자료에 없는 내용으로 구성되어 있습니다.
    - **2점 (다소 벗어남):** 상당 부분이 참고 자료를 벗어난 내용이거나, 참고 자료와 상충되는 정보가 포함되어 있습니다.
    - **1점 (완전 벗어남):** 내용 대부분이 참고 자료와 관련이 없거나, 명백히 참고 자료와 다른 허위 정보를 포함하고 있습니다.

    ## 평가 절차
    1. 제공된 참고 자료를 주의 깊게 읽고 주요 사실과 세부 정보를 파악합니다.
    2. `생성된 지문`의 각 내용이 참고 자료에서 근거를 찾을 수 있는지 확인합니다.
    3. 참고 자료를 벗어난 내용의 정도에 따라 점수를 부여합니다.

    ## 입력 형식
    **참고 자료:**
    * 한국 문화 ({korean_topic}): {korean_context}
    * 외국 문화 ({foreign_topic}): {foreign_context}
    **생성된 지문:**
    {passage}

    ## 출력 형식 (점수만 기입)
    - 참고 자료 기반성 (Reference Groundedness):

  # 4. 논리적 흐름 및 구조(Logical Flow) 평가 프롬프트
  logical_flow: |
    # 논리적 흐름 및 구조(Logical Flow) 평가 안내서

    ## 역할
    당신은 글쓰기 구조 분석 전문가로서, `생성된 지문`을 보고 지문의 **논리적 흐름 및 구조**를 평가하는 과제를 수행합니다.

    ## 평가 기준
    * **논리적 흐름 및 구조 (Logical Flow):** 글이 도입-본론-결론과 같은 명확한 구조를 가지고 있으며, 문장과 문단 간의 연결이 논리적으로 자연스러운지를 평가합니다. 단순한 정보 나열이 아닌 체계적인 글의 구성을 확인합니다.

    ## 평가 척도 (1-5점)
    - **5점 (매우 논리적):** 도입-본론-결론의 명확한 구조를 가지고 있으며, 문장과 문단 간의 연결이 매우 논리적이고 자연스럽습니다.
    - **4점 (논리적):** 대체로 논리적인 구조를 가지고 있지만, 일부 연결 부분에서 약간의 어색함이나 비약이 있습니다.
    - **3점 (보통):** 기본적인 구조는 있으나, 논리적 연결이 완전하지 않거나 일부 내용이 단순 나열에 그칩니다.
    - **2점 (다소 비논리적):** 구조가 불분명하고, 문장 간의 연결이 어색하거나 논리적 일관성이 부족합니다.
    - **1점 (매우 비논리적):** 논리적 구조가 전혀 없이 정보를 무작정 나열하거나, 문맥상 연결이 전혀 맞지 않습니다.

    ## 평가 절차
    1. `생성된 지문`의 전체 구조(도입, 본론, 결론)를 파악합니다.
    2. 문장과 문단 간의 논리적 연결성을 확인합니다.
    3. 접속어, 지시어 등의 적절한 사용 여부를 점검합니다.
    4. 전체적인 논리적 흐름을 종합적으로 평가하여 점수를 부여합니다.

    ## 입력 형식
    **생성된 지문:**
    {passage}

    ## 출력 형식 (점수만 기입)
    - 논리적 흐름 및 구조 (Logical Flow):

  # 5. 한국어 품질(Korean Quality) 평가 프롬프트
  korean_quality: |
    # 한국어 품질(Korean Quality) 평가 안내서

    ## 역할
    당신은 국립국어원의 수석 언어 감수 전문가입니다. 당신의 임무는 주어진 텍스트의 문법, 맞춤법, 띄어쓰기, 구두점, 단어 선택, 문맥의 흐름 등 언어적 정확성과 자연스러움을 종합적으로 분석하고 평가하는 것입니다.

    ## 평가 기준
    * **한국어 품질 (Korean Quality):** 지문에 명백한 문법, 맞춤법, 띄어쓰기 오류가 없는지, 원어민이 읽었을 때 어색하거나 번역투로 느껴지는 표현은 없는지를 평가합니다.

    ## 평가 척도 (1-5점)
    - **5점 (매우 우수함):** 문법, 맞춤법, 띄어쓰기가 완벽하고, 자연스러운 한국어 표현으로 구성되어 원어민이 읽기에 전혀 어색함이 없습니다.
    - **4점 (우수함):** 대체로 정확한 한국어이지만, 사소한 문법적 오류나 약간 어색한 표현이 1~2개 정도 있습니다.
    - **3점 (보통):** 의미 전달에는 문제가 없으나, 몇 가지 문법 오류나 부자연스러운 표현이 있어 완전히 자연스럽지는 않습니다.
    - **2점 (다소 부족함):** 여러 문법 오류나 어색한 표현이 있어, 원어민이 읽기에 상당히 부자연스럽거나 번역투가 느껴집니다.
    - **1점 (매우 부족함):** 심각한 문법 오류가 다수 있거나, 한국어로서 부적절한 표현이 많아 이해하기 어렵습니다.

    ## 평가 절차
    1. 주어진 지문의 문법적 정확성을 점검합니다.
    2. 맞춤법, 띄어쓰기, 구두점 사용의 적절성을 확인합니다.
    3. 어휘 선택과 문장 구조의 자연스러움을 평가합니다.
    4. 번역투나 어색한 표현의 유무를 확인합니다.
    5. 종합적으로 평가하여 점수를 부여합니다.

    ## 입력 형식
    **생성된 지문:**
    {passage}

    ## 출력 형식 (점수만 기입)
    - 한국어 품질 (Korean Quality):

  # 6. L2 학습자 적합성(L2 Learner Suitability) 평가 프롬프트
  l2_learner_suitability: |
    # L2 학습자 적합성(L2 Learner Suitability) 평가 안내서

    ## 역할
    당신은 한국어 교육 전문가로서, `생성된 지문`이 **외국인 한국어 학습자(L2 Learner)**에게 적합한지를 평가하는 과제를 수행합니다.

    ## 평가 기준
    * **L2 학습자 적합성 (L2 Learner Suitability):** 지문의 전반적인 어휘 수준과 문장 복잡도가 L2 학습자(중급~고급)에게 적절한지를 평가합니다. 별도의 설명 없이 이해하기 어려운 전문 용어나 배경지식이 필요한 내용은 없는지 확인합니다.

    ## 평가 척도 (1-5점)
    - **5점 (매우 적합함):** L2 학습자가 이해하기에 완벽한 난이도로, 적절한 어휘와 문장 구조를 사용하여 구성되어 있습니다.
    - **4점 (적합함):** 대체로 L2 학습자에게 적절하지만, 일부 어려운 어휘나 복잡한 문장이 있어 약간의 도움이 필요할 수 있습니다.
    - **3점 (보통):** L2 학습자가 이해할 수 있는 수준이지만, 몇 가지 전문 용어나 복잡한 표현으로 인해 완전한 이해에 어려움이 있을 수 있습니다.
    - **2점 (다소 부적합함):** 상당한 전문 용어나 복잡한 문장 구조로 인해 L2 학습자가 이해하기 어려운 부분이 많습니다.
    - **1점 (매우 부적합함):** 지나치게 어려운 어휘나 복잡한 문장 구조로 인해 L2 학습자가 이해하기 매우 어렵습니다.

    ## 평가 절차
    1. 지문에 사용된 어휘의 난이도를 확인합니다.
    2. 문장 구조의 복잡성을 평가합니다.
    3. 전문 용어나 배경지식이 필요한 내용의 유무를 점검합니다.
    4. L2 학습자의 이해 가능성을 종합적으로 평가하여 점수를 부여합니다.

    ## 입력 형식
    **생성된 지문:**
    {passage}

    ## 출력 형식 (점수만 기입)
    - L2 학습자 적합성 (L2 Learner Suitability):

  binary_rubric: |
    너는 iSKA 말하기 평가용으로 생성된 '지문'의 품질을 검수하는 AI **교육 품질(Educational Quality) 전문가**다.
    너의 임무는 주어진 [평가 대상]이 **외국인 한국어 학습자(L2 Learner)**에게 적합한지 아래 6가지 [검수 항목]에 따라 O/X로 평가하고, 그 결과를 지정된 JSON 형식으로만 출력하는 것이다.

    == 검수 항목 (Rubrics) ==
    - 각 항목에 대해 '예(true)' 또는 '아니요(false)'로만 판단한다.

    1.  **평가 지침 완전성 (Completeness for Guidelines):** 생성된 지문의 내용이, 주어진 '평가 지침'에 명시된 3가지 목표를 달성하는 데 필요한 정보를 충분하고 균형 잡히게 포함하고 있는가? 특정 목표에 대한 내용만 편중되어 있지는 않은가?
    2.  **핵심 주제 명확성 (Clarity of Core Theme):** 지문이 하나의 통일되고 명확한 핵심 메시지를 전달하고 있는가? 내용이 산만하거나 주제에서 벗어나는 부분이 있지는 않은가?
    3.  **참고 자료 기반성 (Reference Groundedness):** 생성된 지문의 모든 내용이 함께 제공된 '참고 자료'에 의해서만 뒷받침되는가? (참고 자료에 없는 내용이 포함되면 'false')
    4.  **논리적 흐름 및 구조 (Logical Flow):** 글이 도입-본론-결론과 같은 명확한 구조를 가지고 있으며, 문장과 문단 간의 연결이 논리적으로 자연스러운가? (단순 정보 나열이 아닌가?)
    5.  **한국어 품질 (Korean Quality):** 지문에 사용된 어휘와 문장 구조가 문법적으로 정확하고, 외국인 한국어 학습자가 이해하기에 자연스러운가? (어색하거나 번역투의 표현이 없는가?)
    6.  **L2 학습자 적합성 (L2 Learner Suitability):** 지문의 전반적인 난이도가 외국인 한국어 학습자에게 적절한가? (문맥상 추론하기 어려운 전문 용어나 한자어가 별도의 설명 없이 사용되지는 않았는가?)

    == 최종 출력 형식 (JSON) ==
    - 각 항목의 값은 반드시 boolean (true/false) 이어야 한다.
    - 'X(false)'로 판정한 항목이 있다면, 'feedback'에 그 이유를 간결하게 1~2 문장으로 작성한다.
    
    "is_completeness_for_guidelines": <true/false>,
    "is_clarity_of_core_theme": <true/false>,
    "is_reference_grounded": <true/false>,
    "is_logical_flow": <true/false>,
    "has_high_korean_quality": <true/false>,
    "is_learner_appropriate": <true/false>,
    "feedback": "<만약 false 항목이 있다면, 그에 대한 핵심적인 이유를 요약하여 작성>"
    
    == 평가 대상 ==

    [평가 지침 (이 지문으로 만들 문제의 방향)]:
    1. {problem_type1}: {eval_goal1}
    2. {problem_type2}: {eval_goal2}
    3. {problem_type3}: {eval_goal3}

    [참고 자료]:
    - 한국 문화 ({korean_topic}): {korean_context}
    - 외국 문화 ({foreign_topic}): {foreign_context}

    [생성된 지문]:
    {passage}

  binary_rubric_strict: |
    너는 iSKA 말하기 평가용으로 생성된 '지문'의 품질을 검수하는 AI **품질 보증(QA) 최종 책임자**다.
    너의 임무는 주어진 [평가 대상]이 **L2 학습자**를 위한 평가 문항으로 사용되기에 **완벽한지** 아래 6가지 [검수 항목]에 따라 O/X로 평가하는 것이다.
    평가는 **매우 엄격하고 보수적으로** 진행해야 하며, 조금이라도 기준에 미치지 못하거나 의심스러운 부분이 있다면 반드시 '아니요(false)'로 판정해야 한다.

    == 검수 항목 (Rubrics) ==
    - 각 항목에 대해 '예(true)' 또는 '아니요(false)'로만 판단한다. 사소한 흠결도 용납하지 마라.

    1.  **평가 지침 완전성 (Completeness for Guidelines):** 생성된 지문의 내용이, 주어진 '평가 지침'에 명시된 3가지 목표를 달성하는 데 필요한 정보를 충분하고 균형 잡히게 포함하고 있는가? 특정 목표에 대한 내용만 편중되어 있지는 않은가?
    2.  **핵심 주제 명확성 (Clarity of Core Theme):** 지문이 하나의 통일되고 명확한 핵심 메시지를 전달하고 있는가? 내용이 산만하거나 주제에서 벗어나는 부분이 있지는 않은가?
    3.  **참고 자료 기반성 (Reference Groundedness):** 생성된 지문의 모든 내용이 함께 제공된 '참고 자료'에 의해서만 뒷받침되는가? (참고 자료에 없는 내용이 포함되면 'false')
    4.  **논리적 흐름 및 구조 (Logical Flow):** 글이 도입-본론-결론과 같은 명확한 구조를 가지고 있으며, 문장과 문단 간의 연결이 논리적으로 자연스러운가? (단순 정보 나열이 아닌가?)
    5.  **한국어 품질 (Korean Quality):** 지문에 사용된 어휘와 문장 구조가 문법적으로 정확하고, 외국인 한국어 학습자가 이해하기에 자연스러운가? (어색하거나 번역투의 표현이 없는가?)
    6.  **L2 학습자 적합성 (L2 Learner Suitability):** 지문의 전반적인 난이도가 외국인 한국어 학습자에게 적절한가? (문맥상 추론하기 어려운 전문 용어나 한자어가 별도의 설명 없이 사용되지는 않았는가?)

    == 최종 출력 형식 (JSON) ==
    - 각 항목의 값은 반드시 boolean (true/false) 이어야 한다.
    - 'X(false)'로 판정한 항목이 있다면, 'feedback'에 그 이유를 간결하게 1~2 문장으로 작성한다.

    "is_completeness_for_guidelines": <true/false>,
    "is_clarity_of_core_theme": <true/false>,
    "is_reference_grounded": <true/false>,
    "is_logical_flow": <true/false>,
    "has_high_korean_quality": <true/false>,
    "is_learner_appropriate": <true/false>,
    "feedback": "<만약 false 항목이 있다면, 그에 대한 핵심적인 이유를 요약하여 작성>"

    == 평가 대상 ==

    [평가 지침 (이 지문으로 만들 문제의 방향)]:
    1. {problem_type1}: {eval_goal1}
    2. {problem_type2}: {eval_goal2}
    3. {problem_type3}: {eval_goal3}

    [참고 자료]:
    - 한국 문화 ({korean_topic}): {korean_context}
    - 외국 문화 ({foreign_topic}): {foreign_context}

    [생성된 지문]:
    {passage}