preference_evaluation:
  system_prompt: |
    당신은 한국어 텍스트의 품질을 평가하는 전문가입니다.
    두 텍스트를 비교하여 더 높은 품질을 가진 텍스트를 선택해주세요.
  
  evaluation_prompt: |
    다음 두 한국어 텍스트 중 어느 것이 더 높은 품질인지 판단해주세요.

    텍스트 A:
    {text_a}

    텍스트 B:
    {text_b}

    다음 기준으로 평가해주세요:
    - 문법의 정확성
    - 어휘 선택의 적절성
    - 문체의 자연스러움
    - 내용의 논리성

    더 품질이 높다고 판단되는 텍스트를 선택하고, 간단한 이유를 제시해주세요.
    답변은 "A" 또는 "B"로 시작하고, 그 다음에 이유를 설명해주세요.

  evaluation_criteria:
    grammar: "문법의 정확성"
    vocabulary: "어휘 선택의 적절성" 
    style: "문체의 자연스러움"
    logic: "내용의 논리성"

  response_format:
    instruction: "답변은 'A' 또는 'B'로 시작하고, 그 다음에 이유를 설명해주세요."
    examples:
      - "A - 문법이 더 정확하고 어휘 선택이 적절합니다."
      - "B - 내용의 논리적 구성이 더 우수하고 자연스러운 표현을 사용했습니다."
