# iSKA RM 훈련을 위한 쌍대 비교(Pairwise) 평가 프롬프트
# 최종 수정: 2025-07-29

preference_evaluation:
  # 1. 평가 지침 완전성 (Completeness for Guidelines)
  completeness_for_guidelines: |
    두 개의 한국어 독해 지문 A와 B가 주어집니다.
    두 지문은 모두 아래 [공통 조건]을 바탕으로 생성되었습니다.

    [공통 조건]:
    - 문제 유형: {problem_type1}, {problem_type2}, {problem_type3}
    - 평가 목표: {eval_goal1}, {eval_goal2}, {eval_goal3}

    다음은 생성된 지문의 품질을 평가하는 기준입니다:

    **평가 기준:**
    - 지문이 주어진 3개의 `공통 조건` 각각에 대한 질문을 모두 만들 수 있을 만큼, 충분하고 균형 잡힌 정보를 포함하고 있는가?
    
    위 기준에 따라, 두 지문 중 [평가 지침 완전성] 측면에서 더 우수한 것을 선택하세요.

  # 2. 핵심 주제 명확성 (Clarity of Core Theme)
  clarity_of_core_theme: |
    두 개의 한국어 독해 지문 A와 B가 주어집니다.
    두 지문은 모두 아래 [공통 조건]을 바탕으로 생성되었습니다.

    [공통 조건]:
    - 한국어 주제: {korean_topic}
    - 외국어 주제: {foreign_topic}

    다음은 생성된 지문의 품질을 평가하는 기준입니다:

    **평가 기준:**
    - 지문이 두 주제를 중심으로, 하나의 통일되고 명확한 핵심 메시지를 전달하고 있는가? 내용이 산만하거나 주제에서 벗어나는 부분이 있지는 않은가?

    위 기준에 따라, 두 지문 중 [핵심 주제 명확성] 측면에서 더 우수한 것을 선택하세요.

  # 3. 참고 자료 기반성 (Reference-Groundedness)
  reference_groundedness: |
    두 개의 한국어 독해 지문 A와 B가 주어집니다.
    두 지문은 모두 아래 [공통 조건]을 바탕으로 생성되었습니다.

    [공통 조건]:
    - 한국어 참고 자료: {korean_context}
    - 외국어 참고 자료: {foreign_context}

    다음은 생성된 지문의 품질을 평가하는 기준입니다:

    **평가 기준:**
    - 생성된 지문의 모든 내용이 함께 제공된 `참고 자료`의 정보에 의해서만 뒷받침되는가? 참고 자료에 없거나 상충되는 내용이 포함되지는 않았는가?

    위 기준에 따라, 두 지문 중 [참고 자료 기반성] 측면에서 더 우수한 것을 선택하세요.

  # 4. 논리적 흐름 및 구조 (Logical Flow & Structure)
  logical_flow: |
    두 개의 한국어 독해 지문 A와 B가 주어집니다.

    다음은 생성된 지문의 품질을 평가하는 기준입니다:

    **평가 기준:**
    - 글이 도입-본론-결론과 같은 명확한 구조를 가지고 있으며, 문장 간의 연결이 논리적으로 자연스러운가? 단순 정보 나열이 아닌가?)

    위 기준에 따라, 두 지문 중 [논리적 흐름 및 구조] 측면에서 더 우수한 것을 선택하세요.

  # 5. 한국어 품질 (Korean Quality) - 기존 프롬프트
  korean_quality: |
    두 개의 한국어 독해 지문 A와 B가 주어집니다.

    다음은 생성된 지문의 품질을 평가하는 기준입니다:

    **평가 기준:**
    - 문법, 맞춤법, 띄어쓰기 오류는 없는가?
    - 원어민이 읽었을 때 어색하거나 번역투로 느껴지는 표현은 없는가?
    
    위 기준에 따라, 두 지문 중 [한국어 품질] 측면에서 더 우수한 것을 선택하세요.

  # 6. L2 학습자 적합성 (L2 Learner Suitability)
  l2_learner_suitability: |
    두 개의 한국어 독해 지문 A와 B가 주어집니다.
    
    다음은 생성된 지문의 품질을 평가하는 기준입니다:

    **평가 기준:**
    - 지문의 전반적인 어휘 수준과 문장 복잡도가 L2 학습자에게 적절한가?
    - 별도의 설명 없이 이해하기 어려운 전문 용어나 배경지식이 필요한 내용은 없는가?

    위 기준에 따라, 두 지문 중 [L2 학습자 적합성] 측면에서 더 우수한 것을 선택하세요.