
# 루브릭 기반 지문 평가 프롬프트 (RM_Experiment_v1.0.0.md 기준)

rubric_evaluation:
  completeness_for_guidelines: |
    다음 한국어 지문이 주어진 3개의 평가 목표 각각에 대해 충분하고 균형 잡힌 정보를 포함하고 있는지 평가해주세요.
    
    지문:
    {passage}
    
    평가 기준:
    - 지문이 "자문화와 비교하기" 문항을 만들 수 있을 만큼 충분한 정보를 포함하는가?
    - "원인과 전망 예측하기"에 필요한 단서가 포함되어 있는가?
    - 특정 목표에 대한 내용만 편중되어 있지는 않은가?
    
    판정 기준:
    - PASS: 3개 평가 목표 각각에 대해 질문을 만들 수 있을 만큼 충분하고 균형 잡힌 정보를 포함함
    - FAIL: 특정 목표에만 편중되거나, 일부 목표에 대한 정보가 부족함
    
    답변은 "PASS" 또는 "FAIL"로 시작하고, 그 다음에 상세한 이유를 설명해주세요.

  core_theme_clarity: |
    다음 한국어 지문이 하나의 통일되고 명확한 핵심 메시지를 전달하는지 평가해주세요.
    
    지문:
    {passage}
    
    평가 기준:
    - 지문을 한 문장으로 요약했을 때, 주제가 명확히 드러나는가?
    - 주제와 관련 없는 불필요한 정보가 포함되어 있지는 않은가?
    - 내용이 산만하거나 주제에서 벗어나는 부분이 있지는 않은가?
    
    판정 기준:
    - PASS: 하나의 명확한 핵심 메시지를 전달하며, 불필요한 정보가 없음
    - FAIL: 주제가 불명확하거나, 산만하거나, 불필요한 정보가 포함됨
    
    답변은 "PASS" 또는 "FAIL"로 시작하고, 그 다음에 상세한 이유를 설명해주세요.

  reference_groundedness: |
    다음 한국어 지문이 함께 제공된 참고 자료의 정보에만 근거하여 작성되었는지 평가해주세요.
    
    지문:
    {passage}
    참고 자료:
    {reference}
    
    평가 기준:
    - 지문에 포함된 모든 주장과 설명이 참고 자료에서 근거를 찾을 수 있는가?
    - 참고 자료에 없거나, 그 내용과 상충되는 내용이 포함되어 있지는 않은가?
    - 모델이 배경지식을 사용하여 참고 자료에 없는 내용을 추가한 것으로 의심되는 부분이 있지는 않은가?
    
    판정 기준:
    - PASS: 모든 내용이 참고 자료에 근거함
    - FAIL: 참고 자료에 없는 내용이 포함되거나, 상충되는 내용이 있음
    
    답변은 "PASS" 또는 "FAIL"로 시작하고, 그 다음에 상세한 이유를 설명해주세요.

  logical_flow_and_structure: |
    다음 한국어 지문이 도입-본론-결론의 명확한 구조를 가지고 있으며, 문장과 문단 간의 연결이 논리적으로 자연스러운지 평가해주세요.
    
    지문:
    {passage}
    
    평가 기준:
    - 첫 문장이 주제를 효과적으로 소개하고 있는가?
    - 접속어나 지시어가 올바르게 사용되어 문장 간의 관계를 명확히 보여주는가?
    - 문장과 문단 간의 연결이 논리적으로 자연스러운가?
    - 단순 정보 나열이 아닌가?
    
    판정 기준:
    - PASS: 도입-본론-결론 구조가 명확하고, 논리적으로 연결됨
    - FAIL: 구조가 불명확하거나, 논리적 연결이 부족함
    
    답변은 "PASS" 또는 "FAIL"로 시작하고, 그 다음에 상세한 이유를 설명해주세요.

  korean_quality: |
    다음 한국어 지문에 명백한 문법, 맞춤법, 띄어쓰기 오류가 없는지, 원어민이 읽었을 때 어색하거나 번역투로 느껴지는 표현이 없는지 평가해주세요.
    
    지문:
    {passage}
    
    평가 기준:
    - 주어와 서술어의 호응이 올바른가?
    - 문맥에 맞지 않는 어색한 어휘나 한자어가 사용되지는 않았는가?
    - 문법, 맞춤법, 띄어쓰기 오류가 없는가?
    - 원어민에게 어색하게 느껴지는 표현이 없는가?
    
    판정 기준:
    - PASS: 문법적으로 정확하고 자연스러운 한국어 표현
    - FAIL: 문법, 맞춤법, 띄어쓰기 오류 또는 어색한 표현이 있음
    
    답변은 "PASS" 또는 "FAIL"로 시작하고, 그 다음에 상세한 이유를 설명해주세요.

  l2_learner_suitability: |
    다음 한국어 지문의 어휘 수준과 문장 복잡도가 L2 학습자(중급~고급)에게 적절한지 평가해주세요.
    
    지문:
    {passage}
    
    평가 기준:
    - 지나치게 길거나 복잡한 문장 구조가 사용되지는 않았는가?
    - 별도의 설명 없이 이해하기 어려운 전문 용어나 배경지식이 필요한 내용은 없는가?
    - 학습자가 문맥만으로 의미를 추론하기 어려운 관용 표현이나 신조어가 사용되었는가?
    
    판정 기준:
    - PASS: L2 학습자가 이해하기 적절한 어휘와 문장 구조
    - FAIL: 지나치게 복잡하거나, 이해하기 어려운 표현/용어가 있음
    
    답변은 "PASS" 또는 "FAIL"로 시작하고, 그 다음에 상세한 이유를 설명해주세요.

# 대조 지문 생성 프롬프트
contrastive_generation:
  relevance_negative: |
    다음 기본 지문을 바탕으로, 주제 연관성이 떨어지는 지문을 생성해주세요.
    원본의 길이와 형식은 유지하되, 주제에서 벗어나는 내용으로 수정하세요.
    
    기본 지문:
    {base_passage}
    
    요구사항:
    - 원본과 비슷한 길이 유지
    - 주제와 관련성이 낮은 내용으로 변경
    - 자연스러운 한국어 문체 유지
    
    수정된 지문만 출력해주세요.

  fluency_negative: |
    다음 기본 지문을 바탕으로, 유창성이 떨어지는 지문을 생성해주세요.
    어색한 번역체나 문법 오류를 의도적으로 포함시켜주세요.
    
    기본 지문:
    {base_passage}
    
    요구사항:
    - 원본과 비슷한 길이 유지
    - 어색한 번역체 표현 사용
    - 문법적 오류 포함
    - 부자연스러운 어휘 선택
    
    수정된 지문만 출력해주세요.

  accuracy_negative: |
    다음 기본 지문을 바탕으로, 사실적 정확성이 떨어지는 지문을 생성해주세요.
    의도적으로 사실 오류나 논리적 모순을 포함시켜주세요.
    
    기본 지문:
    {base_passage}
    
    요구사항:
    - 원본과 비슷한 길이 유지
    - 명백한 사실 오류 포함
    - 논리적 모순 포함
    - 모순되는 정보 제시
    
    수정된 지문만 출력해주세요.

  completeness_negative: |
    다음 기본 지문을 바탕으로, 완전성이 떨어지는 지문을 생성해주세요.
    중요한 정보를 의도적으로 누락시키거나 불완전하게 만들어주세요.
    
    기본 지문:
    {base_passage}
    
    요구사항:
    - 원본보다 짧게 만들기
    - 중요한 정보 누락
    - 설명의 불완전성
    - 결론 부분 생략
    
    수정된 지문만 출력해주세요.

  coherence_negative: |
    다음 기본 지문을 바탕으로, 일관성이 떨어지는 지문을 생성해주세요.
    논리적 비약이나 일관성 부족을 의도적으로 만들어주세요.
    
    기본 지문:
    {base_passage}
    
    요구사항:
    - 원본과 비슷한 길이 유지
    - 논리적 비약 포함
    - 일관성 없는 주장
    - 문단 간 연결성 부족
    
    수정된 지문만 출력해주세요.
