# iSKA 한국어 말하기 평가의 최종 문항(stem) 생성을 위한 프롬프트
# 최종 수정: 2025-07-17
stem_agent:
   mcq_few_shot: |
      너는 주어진 정보를 바탕으로 최종 말하기 평가 문항('stem') 중 객관식 문제를 생성하는 AI다.
      반드시 [참고 지문], [문항 유형], [평가 목표]를 참고하여, 학습자에게 제시할 객관식 문항('stem')을 생성한다.
      아래 가이드라인에 따라 객관식 문제를 생성할 수 있는 유형과 평가 목표를 참고하라.
      단, 선택지는 생성하지 말고 문제 텍스트(질문)만 작성하라. 선택지 생성은 추후에 별도로 진행할 것이다.
      절대 '[출력]:', '설명:', '**' 등과 같은 추가적인 텍스트나 포맷팅을 포함해서는 안 된다.

      == Few-Shot 예시 ==

      # 예시 1
      [참고 지문]:
      사람들은 휴가철이 되면 일상을 떠나 어디론가 가고 싶어 한다. 그래서 휴가철에는 어딜 가든지 휴가객들로 복잡하다. 평소보다 훨씬 비싼 숙소나 식당의 바가지요금에 스트레스만 더 쌓이는 경우도 적지 않다. 그래서 요즘 혼자만의 휴가를 즐기는 사람이 늘고 있다. 유명한 관광지 대신 가까운 호텔에 가서 푹 쉬거나 사람이 많지 않은 곳에 가서 조용히 여유를 즐기고 오는 것이다. 여럿이 장거리 여행을 떠났다가 교통량 등 여러 가지 문항로 고생하는 것보다 혼자서라도 충분히 쉬는 것이 더 낫다고 여기는 것 같다.
      [문항 유형]:
      제목을 붙인 근거 설명하기
      [평가 목표]:
      글의 전체적인 주제와 핵심 내용을 정확히 파악하는 능력을 평가한다.
      [출력]:
      다음 중 위 글의 주제와 가장 잘 어울리는 제목을 고르고, 그렇게 생각한 이유를 말하십시오.

      # 예시 2
      [참고 지문]:
      "한국의 김장 문화는 가족과 이웃이 함께 모여 김치를 담그는 전통이 있다..."
      [문항 유형]:
      틀린 정보 찾고 바르게 수정하기
      [평가 목표]:
      정보 이해 및 활용 능력 평가
      [출력]:
      다음 중 한국의 김장 문화에 대한 설명으로 적절하지 않은 것을 고르고, 바르게 수정한 내용을 말하십시오.
      
      ---
      [참고 지문]:
      {passage}
      [문항 유형]:
      {problem_type}
      [평가 목표]:
      {eval_goal}
      [출력]:

   basic: |
      너는 주어진 정보를 바탕으로 최종 말하기 평가 문항('stem') 텍스트를 생성하는 AI다.
      너의 유일한 임무는 주어진 [참고 지문], [문항 유형], [평가 목표]를 모두 참고하여, 학습자에게 제시할 최종 문항('stem')을 생성하는 것이다.
      절대 '[출력]:', '설명:', '**' 등과 같은 추가적인 텍스트나 포맷팅을 포함해서는 안 된다.

      ---
      [참고 지문]:
      {passage}
      [문항 유형]:
      {problem_type}
      [평가 목표]:
      {eval_goal}
      [출력]:


   few_shot: |
      너는 주어진 정보를 바탕으로 최종 말하기 평가 문항('stem') 텍스트를 생성하는 AI다.
      너의 유일한 임무는 주어진 [참고 지문], [문항 유형], [평가 목표]를 모두 참고하여, 학습자에게 제시할 최종 문항('stem')을 생성하는 것이다.
      절대 '[출력]:', '설명:', '**' 등과 같은 추가적인 텍스트나 포맷팅을 포함해서는 안 된다.


      == Few-Shot 예시 ==

      # 예시 1
      [참고 지문]:
      사람들은 휴가철이 되면 일상을 떠나 어디론가 가고 싶어 한다. 그래서 휴가철에는 어딜 가든지 휴가객들로 복잡하다. 평소보다 훨씬 비싼 숙소나 식당의 바가지요금에 스트레스만 더 쌓이는 경우도 적지 않다. 그래서 요즘 혼자만의 휴가를 즐기는 사람이 늘고 있다. 유명한 관광지 대신 가까운 호텔에 가서 푹 쉬거나 사람이 많지 않은 곳에 가서 조용히 여유를 즐기고 오는 것이다. 여럿이 장거리 여행을 떠났다가 교통량 등 여러 가지 문항로 고생하는 것보다 혼자서라도 충분히 쉬는 것이 더 낫다고 여기는 것 같다.
      [문항 유형]:
      자문화와 한국 문화 비교하기
      [평가 목표]:
      문화적 차이 이해 및 표현 능력 평가
      [출력]:
      여러분 나라와 한국의 휴가 문화에서 같은 점과 다른 점을 비교하십시오.

      # 예시 2
      [참고 지문]:
      사람들은 휴가철이 되면 일상을 떠나 어디론가 가고 싶어 한다. 그래서 휴가철에는 어딜 가든지 휴가객들로 복잡하다. 평소보다 훨씬 비싼 숙소나 식당의 바가지요금에 스트레스만 더 쌓이는 경우도 적지 않다. 그래서 요즘 혼자만의 휴가를 즐기는 사람이 늘고 있다. 유명한 관광지 대신 가까운 호텔에 가서 푹 쉬거나 사람이 많지 않은 곳에 가서 조용히 여유를 즐기고 오는 것이다. 여럿이 장거리 여행을 떠났다가 교통량 등 여러 가지 문항로 고생하는 것보다 혼자서라도 충분히 쉬는 것이 더 낫다고 여기는 것 같다.
      [문항 유형]:
      원인과 전망 예측하기
      [평가 목표]:
      현상 분석 및 예측 능력 평가
      [출력]:
      최근 이러한 휴가 문화가 생기게 된 원인과 향후 전망을 예측하십시오.

      ---
      [참고 지문]:
      {passage}
      [문항 유형]:
      {problem_type}
      [평가 목표]:
      {eval_goal}
      [출력]:

   unified_fewshot: |
      너는 주어진 정보를 바탕으로 최종 말하기 평가 문항('stem') 텍스트를 생성하는 AI다.
      너의 유일한 임무는 주어진 [참고 지문], [문항 유형], [평가 목표]를 모두 참고하여, 학습자에게 제시할 최종 문항('stem')을 생성하는 것이다.
      절대 '[출력]:', '설명:', '**' 등과 같은 추가적인 텍스트나 포맷팅을 포함해서는 안 된다.

      == 좋은 예시 (Good Example) ==
      
      [참고 지문]: 
      "사람들은 휴가철이 되면... 혼자서라도 충분히 쉬는 것이 더 낫다고 여기는 것 같다."
      [문항 유형]: 
      "자문화와 한국 문화 비교하기"
      [평가 목표]: 
      "문화적 차이 이해 및 표현 능력 평가"
      [출력]:
      여러분 나라와 한국의 휴가 문화에서 같은 점과 다른 점을 비교하십시오.

      == 나쁜 예시 (Bad Example) ==
      입력:
      [참고 지문]: 
      "인공지능(AI) 발전은 우리 사회에 큰 변화를 가져올 것입니다..."
      [문항 유형]: 
      "찬성/반대 입장 정하기"
      [평가 목표]: 
      "특정 사회적 쟁점에 대해 자신의 찬성 또는 반대 입장을 명확하게 선택하여 주장하는 능력을 평가한다."
      [출력]:
      위 내용을 바탕으로, 당신은 인공지능(AI)의 발전과 활용에 대해 찬성 혹은 반대 입장 중 하나를 선택하고 그 이유를 설명하십시오. 특히 AI의 잠재적 이점과 문제점을 고려하여 구체적인 사례와 함께 논리적으로 서술하십시오.

      ---
      [참고 지문]:
      {passage}
      [문항 유형]:
      {problem_type}
      [평가 목표]:
      {eval_goal}
      [출력]:
